# === Batch Runner Config (CloudInfraAgent) ===

# How often the scheduler triggers (used by scheduler.py)
schedule_hours: 6

# IMPORTANT: these point to your existing layout
inputs_root: "cloud_infra_agent/Data/Inputs"
outputs_root: "cloud_infra_agent/Data/Outputs"
state_file: "cloud_infra_agent/Data/state/processed.json"

# A batch is processable if it has at least one JSON file
file_glob_patterns:
  - "*.json"

# How to call the engine:
# Option A (default here): call Python adapter that reads per-metric JSONs
engine_command: ""
engine_callable: "batch_runner.engine_adapter:run_engine"
