default_filenames:
  baseline_schema: "baseline_table.json"
  table_schemas: "real_table.json"
  table_metadata: "table_metadata.json"
  data_quality_report: "quality_input_3.json"
  access_logs: "governance_input_4.json"
  lineage: "lineage_input_5.json"
  metadata: "metadata_input_6.json"
  tagging: "sensetive_tagging_input_7.json"
  duplication: "duplication_input_8.json"
  backup: "backup_input_9.json"
  security: "security_input_10.json"
  pipeline_runs: "pipeline_success_input_b1.json"
  pipeline_metrics: "pipeline_latency_input_b2.json"
  resource_usage: "resource_utilization_input_b3.json"
  query_logs: "query_performance_input_b4.json"
  user_activity: "analytics_adoption_input_b5.json"
