BASELINE_PATH: "data/Input/baseline_table.json"
TABLES_PATH: "data/Input/real_table.json"
OUTPUT_PATH: "data/Output/output.json"

FRESHNESS_INPUT_PATH: "data/Input/table_metadata.json"
FRESHNESS_OUTPUT_PATH: "data/Output/output2.json"

QUALITY_INPUT_PATH: "data/Input/quality_input_3.json"
QUALITY_OUTPUT_PATH: "data/Output/output_quality_3.json"

GOVERNANCE_INPUT_PATH: "data/Input/governance_input_4.json"
GOVERNANCE_OUTPUT_PATH: "data/Output/governance_output_4.json"

LINEAGE_INPUT_PATH: "data/Input/lineage_input_5.json"
LINEAGE_OUTPUT_PATH: "data/Output/lineage_output_5.json"

METADATA_INPUT_PATH: "data/Input/metadata_input_6.json"
METADATA_OUTPUT_PATH: "data/Output/metadata_output_6.json"

TAGGING_INPUT_PATH: "data/Input/sensetive_tagging_output_7.json"
TAGGING_OUTPUT_PATH: "data/Output/sensetive_tagging_output_7.json"

DUPLICATION_INPUT_PATH: "data/Input/duplication_input_8.json"
DUPLICATION_OUTPUT_PATH: "data/Output/duplication_output_8.json"

BACKUP_INPUT_PATH: "data/Input/backup_input_9.json"
BACKUP_OUTPUT_PATH: "data/Output/backup_output_9.json"

SECURITY_INPUT_PATH: "data/Input/security_input_10.json"
SECURITY_OUTPUT_PATH: "data/Output/security_output_10.json"



# Input JSON files for Analytics Readiness metrics
PIPELINE_SUCCESS_INPUT_PATH: "data/Input/pipeline_success_input_b1.json"
PIPELINE_LATENCY_INPUT_PATH: "data/Input/pipeline_latency_input_b2.json"
RESOURCE_UTIL_INPUT_PATH: "data/Input/resource_utilization_input_b3.json"
QUERY_PERFORMANCE_INPUT_PATH: "data/Input/query_performance_input_b4.json"
ANALYTICS_ADOPTION_INPUT_PATH: "data/Input/analytics_adoption_input_b5.json"

# Output JSON files
PIPELINE_SUCCESS_OUTPUT_PATH: "data/Output/pipeline_success_rate_output_b1.json"
PIPELINE_LATENCY_OUTPUT_PATH: "data/Output/pipeline_latency_output_b2.json"
RESOURCE_UTIL_OUTPUT_PATH: "data/Output/resource_utilization_output_b3.json"
QUERY_PERFORMANCE_OUTPUT_PATH: "data/Output/query_performance_output_b4.json"
ANALYTICS_ADOPTION_OUTPUT_PATH: "data/Output/analytics_adoption_output_5.json"
